x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

volumes:
  postgres-lemmy-data:
  postgres-wrapper-data:
  pictrs-data:

networks:
  we4us-network:
    driver: bridge

services:
  we4us:
    image: yashaswinisharma/we4us-we4us-deploy:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_LEMMY_API_URL=https://we4us.co.in
      - VITE_PHOENIX_URL=https://we4us.co.in/phoenix
      - VITE_WEBSOCKET_URL=wss://we4us.co.in/socket

    depends_on:
      - postgres-wrapper
      - lemmy
    networks:
      - we4us-network
    restart: always
    logging: *default-logging

  postgres-wrapper:
    image: yashaswinisharma/we4us-phx-deploy:latest
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@postgres-wrapper-db/we4us_dev
      - SECRET_KEY_BASE=Temp_Value
      - LEMMY_API_URL=http://lemmy:8536/api/v3
    depends_on:
      - postgres-wrapper-db
    networks:
      - we4us-network
    restart: always
    logging: *default-logging
    mem_limit: 2g

  postgres-wrapper-db:
    image: postgres:16-alpine
    volumes:
      - postgres-wrapper-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=we4us_dev
    networks:
      - we4us-network
    restart: unless-stopped
    logging: *default-logging

  proxy:
    image: nginx:1-alpine
    ports:
      - "80:80"
      - "443:1236"
    volumes:
      - ./lemmy_docker_server/nginx_internal.conf:/etc/nginx/nginx.conf:ro,Z
      - ./lemmy_docker_server/proxy_params:/etc/nginx/proxy_params:ro,Z
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    logging: *default-logging
    depends_on:
      - pictrs
      #- lemmy-ui
      - we4us
    networks:
      - we4us-network

  lemmy:
    image: dessalines/lemmy:0.19.8
    hostname: lemmy
    restart: always
    logging: *default-logging
    environment:
      - RUST_LOG="warn"
    volumes:
      - ./lemmy_docker_server/lemmy.hjson:/config/config.hjson:Z
    depends_on:
      - postgres-lemmy
      - pictrs
    networks:
      - we4us-network

  # lemmy-ui:
  #   image: dessalines/lemmy-ui:0.19.8
  #   environment:
  #     - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
  #     - LEMMY_UI_LEMMY_EXTERNAL_HOST=we4us.co.in/lemmy
  #     - LEMMY_UI_HTTPS=false
  #   volumes:
  #     - ./lemmy_docker_server/volumes/lemmy-ui/extra_themes:/app/extra_themes
  #   depends_on:
  #     - lemmy
  #   restart: always
  #   logging: *default-logging
  #   networks:
  #     - we4us-network

  pictrs:
    image: asonix/pictrs:0.5.16
    hostname: pictrs
    environment:
      - PICTRS__SERVER__API_KEY=lemmy_pwd
      - RUST_BACKTRACE=full
      - PICTRS__MEDIA__VIDEO__VIDEO_CODEC=vp9
      - PICTRS__MEDIA__ANIMATION__MAX_WIDTH=256
      - PICTRS__MEDIA__ANIMATION__MAX_HEIGHT=256
      - PICTRS__MEDIA__ANIMATION__MAX_FRAME_COUNT=400
    command: >
      sh -c "mkdir -p /mnt/pictrs/files /mnt/exports /mnt/sled-repo &&
       /usr/local/bin/pict-rs run"
    user: 991:991
    volumes:
      - pictrs-data:/mnt
    restart: always
    logging: *default-logging
    networks:
      - we4us-network

  postgres-lemmy:
    image: pgautoupgrade/pgautoupgrade:17-alpine
    hostname: postgres
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=lemmy_pwd
      - POSTGRES_DB=lemmy
    shm_size: 1g
    volumes:
      - postgres-lemmy-data:/var/lib/postgresql/data:Z
      - ./lemmy_docker_server/customPostgresql.conf:/etc/postgresql.conf
    restart: always
    logging: *default-logging
    networks:
      - we4us-network

  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname=lemmy
    restart: always
    logging: *default-logging
    networks:
      - we4us-network

