x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

# Uncomment this and fix line 83
# If you're having issues persisting data (especially if on windows/WSL)
#volumes:
  #postgres-data:

services:
  proxy:
    image: nginx:1-alpine
    ports:
      # Listen for outside connections on port 10633. You can freely change the left-side
      # number to a different port, eg using port 80 if you don't need a reverse proxy.
      - "10633:8536"
    volumes:
      - ./nginx_internal.conf:/etc/nginx/nginx.conf:ro,Z
      - ./proxy_params:/etc/nginx/proxy_params:ro,Z
    restart: always
    logging: *default-logging
    depends_on:
      - pictrs
      - lemmy-ui

  lemmy:
    image: dessalines/lemmy:0.19.8
    hostname: lemmy
    restart: always
    logging: *default-logging
    environment:
      - RUST_LOG="warn"
      - LEMMY_SETUP_ADMIN_USERNAME=cohort2_user2
      - LEMMY_SETUP_ADMIN_PASSWORD=nishita123
      - LEMMY_SETUP_ADMIN_EMAIL=admin@localhost
      - LEMMY_SETUP_SITE_NAME=WE4US
      - LEMMY_SETUP_SITE_DESCRIPTION=A platform for students to connect, share, and grow.
      - LEMMY_SETUP_ENABLE_DOWNVOTES=true
      - LEMMY_SETUP_ENABLE_NSFW=true
      - LEMMY_SETUP_COMMUNITY_CREATION_ADMIN_ONLY=true
      - LEMMY_SETUP_REQUIRE_EMAIL_VERIFICATION=false
      - LEMMY_SETUP_PRIVATE_INSTANCE=true
      - LEMMY_SETUP_FEDERATION_ENABLED=false
      - LEMMY_SETUP_COMMUNITIES=job_board:Job Board:List job and internship openings,announcements:Announcements:Important announcements and updates,pg_finder:PG Finder:PG recommendations with reviews,meet_up:Meet Up:Upcoming meet-up events and activities
    volumes:
      - ./lemmy.hjson:/config/config.hjson:Z
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: dessalines/lemmy-ui:0.19.8
    environment:
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=lemmy.ml
      - LEMMY_UI_HTTPS=true
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes
    depends_on:
      - lemmy
    restart: always
    logging: *default-logging

  pictrs:
    image: asonix/pictrs:0.5.16
    # this needs to match the pictrs url in lemmy.hjson
    hostname: pictrs
    # we can set options to pictrs like this, here we set max. image size and forced format for conversion
    # entrypoint: /sbin/tini -- /usr/local/bin/pict-rs -p /mnt -m 4 --image-format webp
    environment:
      - PICTRS_OPENTELEMETRY_URL=http://otel:4137
      - PICTRS__SERVER__API_KEY=lemmy_pwd
      - RUST_BACKTRACE=full
      - PICTRS__MEDIA__VIDEO__VIDEO_CODEC=vp9
      - PICTRS__MEDIA__ANIMATION__MAX_WIDTH=256
      - PICTRS__MEDIA__ANIMATION__MAX_HEIGHT=256
      - PICTRS__MEDIA__ANIMATION__MAX_FRAME_COUNT=400
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt:Z
    restart: always
    logging: *default-logging

  postgres:
    image: pgautoupgrade/pgautoupgrade:17-alpine
    hostname: postgres
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=lemmy_pwd
      - POSTGRES_DB=lemmy
    shm_size: 1g
    volumes:
      - /var/lib/postgresql/data
      # replace the above line with postgres-data:/var/lib/postgresql/data:Z if needed
      - ./customPostgresql.conf:/etc/postgresql.conf
    restart: always
    logging: *default-logging

  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname=lemmy:8765
    restart: "always"
    logging: *default-logging
s